/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : EInt.h
**     Project     : kpb17
**     Processor   : SKEAZ64MLH4
**     Component   : ExtInt_LDD
**     Version     : Component 02.156, Driver 01.02, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2023-04-15, 13:12, # CodeGen: 12
**     Abstract    :
**         This component, "ExtInt_LDD", provide a low level API 
**         for unified access of external interrupts handling
**         across various device designs.
**         The component uses one pin which generates interrupt on 
**         selected edge.
**     Settings    :
**          Component name                                 : EInt
**          Pin                                            : PTI4/IRQ
**          Generate interrupt on                          : rising edge
**          Interrupt                                      : INT_IRQ
**          Interrupt priority                             : low priority
**          ISR Name                                       : EInt_Interrupt
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**     Contents    :
**         Init    - LDD_TDeviceData* EInt_Init(LDD_TUserData *UserDataPtr);
**         Deinit  - void EInt_Deinit(LDD_TDeviceData *DeviceDataPtr);
**         Enable  - void EInt_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable - void EInt_Disable(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file EInt.h
** @version 01.02
** @brief
**         This component, "ExtInt_LDD", provide a low level API 
**         for unified access of external interrupts handling
**         across various device designs.
**         The component uses one pin which generates interrupt on 
**         selected edge.
*/         
/*!
**  @addtogroup EInt_module EInt module documentation
**  @{
*/         

#ifndef __EInt_H
#define __EInt_H

/* MODULE EInt. */

#include "Cpu.h"
/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "GPIO_PDD.h"
#include "IRQ_PDD.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 

/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define EInt_PRPH_BASE_ADDRESS  0x400FF080U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define EInt_Init_METHOD_ENABLED       /*!< Init method of the component EInt is enabled (generated) */
#define EInt_Deinit_METHOD_ENABLED     /*!< Deinit method of the component EInt is enabled (generated) */
#define EInt_Enable_METHOD_ENABLED     /*!< Enable method of the component EInt is enabled (generated) */
#define EInt_Disable_METHOD_ENABLED    /*!< Disable method of the component EInt is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */
#define EInt_OnInterrupt_EVENT_ENABLED /*!< OnInterrupt event of the component EInt is enabled (generated) */

/* Definition of implementation constants */
#define EInt_PIN_INDEX 0x04U           /*!< Index of the used pin from the port */
#define EInt_PIN_MASK 0x10U            /*!< Mask of the used pin from the port */

/*
** ===================================================================
**     Method      :  EInt_Init (component ExtInt_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* EInt_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  EInt_Deinit (component ExtInt_LDD)
*/
/*!
**     @brief
**         This method disables the device and frees the device data
**         structure memory.
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure pointer.
*/
/* ===================================================================*/
void EInt_Deinit(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  EInt_Enable (component ExtInt_LDD)
*/
/*!
**     @brief
**         Enable the component - the external events are accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void EInt_Enable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  EInt_Disable (component ExtInt_LDD)
*/
/*!
**     @brief
**         Disable the component - the external events are not accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void EInt_Disable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  EInt_Interrupt (component ExtInt_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/* {Default RTOS Adapter} ISR function prototype */
PE_ISR(EInt_Interrupt);

/* END EInt. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __EInt_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
